# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'course_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ourse_service.proto\x12\x0b\x63ourservice\"%\n\x10GetCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\t\"J\n\x11GetCourseResponse\x12\x11\n\tcourse_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t2[\n\rCourseService\x12J\n\tGetCource\x12\x1d.courservice.GetCourseRequest\x1a\x1e.courservice.GetCourseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCOURSEREQUEST']._serialized_start=37
  _globals['_GETCOURSEREQUEST']._serialized_end=74
  _globals['_GETCOURSERESPONSE']._serialized_start=76
  _globals['_GETCOURSERESPONSE']._serialized_end=150
  _globals['_COURSESERVICE']._serialized_start=152
  _globals['_COURSESERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
